package net.nvcm.korzun.blz.client;

import org.apache.cxf.annotations.Logging;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.0-milestone2
 * 2017-03-31T14:46:53.863+02:00
 * Generated source version: 3.0.0-milestone2
 * 
 */
@WebService(targetNamespace = "http://thomas-bayer.com/blz/", name = "BLZServicePortType")
@XmlSeeAlso({ObjectFactory.class})
@Logging
public interface BLZServicePortType {

    @WebMethod
    @Action(output = "http://thomas-bayer.com/blz/BLZService/getBankResponse")
    @RequestWrapper(localName = "getBank", targetNamespace = "http://thomas-bayer.com/blz/", className = "net.nvcm.korzun.blz.client.GetBankType")
    @ResponseWrapper(localName = "getBankResponse", targetNamespace = "http://thomas-bayer.com/blz/", className = "net.nvcm.korzun.blz.client.GetBankResponseType")
    @WebResult(name = "details", targetNamespace = "http://thomas-bayer.com/blz/")
    public net.nvcm.korzun.blz.client.DetailsType getBank(
        @WebParam(name = "blz", targetNamespace = "http://thomas-bayer.com/blz/")
        java.lang.String blz
    );
}
